[build]
  functions = "functions/"
  command = "npm run build"  # The build command for your Vite project
  publish = "dist"           # The directory to deploy (output directory after build)
[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200